name: Bug report
description: Create a bug report to help us improve
labels:
    - bug
body:
    - type: markdown
      attributes:
          value: >
              Thank you for taking the time to fill out a bug report.
              Remember to fill out all required fields, including the title above.
    - type: textarea
      id: current
      attributes:
          label: Current Behaviour
          description: >
              Describe the problem or bug that you are encountering.
              If applicable, add screenshots, images, or videos to help explain your problem.
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behaviour
          description: |
              What should happen instead?
      validations:
          required: false
    - type: textarea
      id: reproduce
      attributes:
          label: Reproduction steps
          description: |
              What does someone else need to do to encounter the same bug?
          placeholder: |
              1. Step 1
              2. Step 2
              3. Step 3
      validations:
          required: true
    - type: input
      id: server-specs
      attributes:
          label: Server operating system
          description: |
              What OS do you run Strapi on? (name, version, etc)
      validations:
          required: true
    - type: input
      id: client-specs
      attributes:
          label: Client operating system and browser
          description: |
              What OS and web browser does the issue occur on? (names and versions)
      validations:
          required: true
    - type: input
      id: plugin-version
      attributes:
          label: Plugin version
          description: >
              Which version of `strapi-azerothcore` are you using?
              Copy the version next to `strapi-azerothcore` in the `dependencies` section of your `package.json` file in your Strapi project.
      validations:
          required: true
    - type: input
      id: ac-commit
      attributes:
          label: AzerothCore revision (commit hash)
          description: >
              The version of your AzerothCore server.
              You can copy the first line from the `.server info` command's output.
      validations:
          required: false
